project_name       = "TechScrum"
aws_region         = "ap-southeast-2"
Master_Server_Name = "Jenkins Master"
Slave_Server_Name  = "Jenkins Slave"
ami                = "ami-04f5097681773b989"
instance_type      = "t2.micro"
key_name           = "test"
