name: 'Terraform'

on:
  workflow_dispatch:


# permissions:
#   contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials For
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRECT_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Format
        run: terraform fmt -check
  
      - name: Terraform Plan
        run: terraform plan -var-file="test.tfvars" -input=false
  
      - name: Terraform Apply
        run: terraform apply -var-file="test.tfvars" -auto-approve -input=false
