name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Please select the terraform action to run:'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials For
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRECT_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
  
      - if: ${{ (github.event.inputs.action == 'deploy') }}
        name: Terraform plan to deploy
        run: terraform plan -var-file="jenkins.tfvars" -input=false

      - if: ${{ (github.event.inputs.action == 'destroy') }}
        name: Terraform plan to Destroy
        run: terraform plan -var-file="jenkins.tfvars" -input=false -destroy
  
      - if: ${{ (github.event.inputs.action == 'deploy') }}
        name: Terraform Deploy
        run: terraform apply -var-file="jenkins.tfvars" -auto-approve -input=false

      - if: ${{ (github.event.inputs.action == 'destroy') }}
        name: Terraform Destroy
        run: terraform destroy -var-file="jenkins.tfvars" -auto-approve -input=false
        
